### ISSUE TITLE
Stremio add-ons

### ISSUE THREAD

**Issue by HVR88** [Unlearned6688/unraid-templates#2]
I'm not sure what the point is of hosting Stremio in docker with no addons. Stremio without add-ons is a web player that can't play anything.

How do you get addons into the docker? Debrid search, Torrentio, etc..

**Comment by pmcfernandes** [comment]
In web ui settings edit 127.0.0.1:11470 to your server ip:11470 next authenticate with your current account you already using in desktop application.

Will load all your installed addons on desktop application

**Comment by HVR88** [comment]
Thanks, I'll give it a try. I did forget that add-ons were tied to login ID so that you can set up in one place and use on another.

**Comment by HVR88** [comment]
Couldn't log in until I used reverse proxy to set a TLS cert onto the page.  

The problem with this is that Streaming Server setting always says ERROR, whether it's localhost (127....) or the actual IP of the bridge, or the FQDN. If I load the IP in the browser, then it says connected, but can't log in like that.

**Comment by HVR88** [comment]
OK....  Hope you didn't read the post that I just got rid of because I just got this to work.

I set the docker back to regular bridge instead of custom bridge and skipped the reverse proxy so I can access it with http. This time it successfully logged in and changing the streaming server IP to the server's real IP brought it online.

And once online I see that streaming to the browser in fact works - so the benefit over using a client-side app is obvious here. 

* I also just noticed that we're both from Lisbon and have the same last name. Cool.

**Comment by Unlearned6688** [comment]
Hello,

seems you got things working?

The other user said it above, but just as a "tip" for future users

you can get this up and running for the server portion

reverse proxy that connection

and easily add it to the settings in 

https://web.stremio.com/

(The official publicly hosted stremio web app)

Useful for iOS devices (no Apple app... probably ever)

setup the http server in a container, setup a stremio account on desktop,

then on mobile add https://web.stremio.com/ to your Home Screen

go into the shortcut. Login. Add your ip:port (or reverse proxy url) to the settings, set it to launch in vlc or outplayer, then there you go. It works pretty well. I think it misses out scrobbling because of the app swap from safari to outplayer/vlc, but, 🤷‍♂️ Apple did this not stremio devs.

that's just the "shortcut" path btw. There's no reason you can't also host your own working web app and server if you wish. Just be careful if you reverse proxy the 11470 server and don't lock it down it I assume anyone can use it. I use a local domain (*.local.example.com) and vpn to my router and it works fine that way. Could also vpn to unraid if you have that setup. I'm not sure how the app performs in conjunction with an authentication setup like using authentik or authelia. But that would work too if it actually allows you to authenticate. Or just the ip:port if you don't care about doing so

**Comment by HVR88** [comment]
Thanks for the tips.

Right now my problem is I'm unable to get the server status "online" in the self-hosted webUI when I go through reverse proxy and force HTTPS (with CA cert).  Says Error every time. I'm using Nginx Proxy Manager, which has been working very well with everything else.

I also can't get the server to connect if I put its IP into web.stremio.com (or any variation of the non-hosted web site), even though it works fine via IP on the local web server. Because this is mainly intended for others in the house to use, I'd really like to get it working with FQDN and https like my other services.

Once I get that going then I'll test from outside - I'm running Tailscale right now which has worked well with all my other hosted apps and server WebUIs.

**Comment by Unlearned6688** [comment]
![ip-port-server-and-ip-port-web](https://github.com/user-attachments/assets/20054692-6126-4f1c-afa1-ce3ea03b97d3)
![proxied-server-and-ip-port-web](https://github.com/user-attachments/assets/8cd0b3e5-028f-4810-b28a-810a41aafe99)
![proxied-server-and-proxied-web](https://github.com/user-attachments/assets/352e74a5-5604-492d-84f7-9449952d91f8)

the blurred portions are my reverse proxy https://subdomain.domain.tld

I was able to get all of these working except for proxied web server + ip:port. the other setups all work.

**Comment by HVR88** [comment]
Thanks again for looking at this.

I've added STREAM Proxies in NPM which send specified ports to your choice of IP:port. I've created entries for 11470 and 12470 (read about that port being used for secure server connection)

**http IP webUI with http IP:11470 server works.** 

<img width="695" alt="image" src="https://github.com/user-attachments/assets/0984f082-c2b4-4d64-b4aa-cdb5b1f5b79f">


**http IP or FQDN webUI with http FQDN:11470 server works**

<img width="550" alt="image" src="https://github.com/user-attachments/assets/3aa04854-aa3a-48d2-8fd5-d624fc2f45f8">


**https server on port 11470 or 12470 always error, whether I connect to the webUI on IP or FQDN https**

<img width="547" alt="image" src="https://github.com/user-attachments/assets/15730ddc-ec50-4f97-b614-c12beb970ef3">

And of course it obviously also fails trying http server when using https on the webUI.

I don't see anything relevant coming up in the log that can be viewed in the docker (Unraid's docker menu)

**Comment by Unlearned6688** [comment]
![IMG_6219](https://github.com/user-attachments/assets/1b5745cc-a4e7-4e6e-95c1-ad3de5030321)
![IMG_6220](https://github.com/user-attachments/assets/98cc6eeb-bcde-4a0e-9f73-dfe7c940df42)

apologies for the delay and half reply above. Life distractions around me.

these are my unraid template and NPM settings.

note that I proxy the http server ip:port

And a separate subdomain for the webpage (I changed the port from 8080 on the host purely as a test earlier today. Shouldn't matter.)

the rest of my settings are basically default.

so for you, I would try:

Reverse proxy both the webpage (the ip:8080 one) maybe name it like stremio.domain.tld (or whatever). Make another entry for the stremio server (ip:11470). Maybe name it stremio-server.domain.tld. 

I would personally just continue to use http. This docker image/project supports https, but, you're reverse proxying it anyway. So, just keep it simple with the http port. It absolutely does work. You can see mine works. That's my opinion anyway.

I think your main issue at this moment was not having two subdomains. One for the web app side, one for the server side.

if I'm wrong about that, if you did already have two subdomains like my setup, then maybe try swapping that 8080 to... something else. But I' pretty sure you just need to reverse proxy the two IPs.

let me know!

**Comment by HVR88** [comment]
Beautiful, it worked with two subdomains.  Thanks!

I had come to the conclusion that it was likely the proxy causing the issue because it already specifies a specific port for the webUI that likely causes a problem for the server port. As it was getting late, I thought I'd ask tomorrow if you actually had the server settings using the same subdomain or if you had split them.  

Now I can likely get the kids to use this without coming back to me with "it says the page isn't secure...." hahaha.

**Comment by Unlearned6688** [comment]
Very good! Glad I could help.
I’m going to close this issue as it seems solved. I’ll also add this information (eventually…) to my little “readme” for this template. Should help people in the future.
Have a good one.

**Comment by HVR88** [comment]
Here's a summary:

- Docker set up as Bridge in Unraid (which uses host's IP) - optionally changing host-side port(s)
- Set up TWO reverse proxy entries with different subdomains: 1. for the webUI pointing to IP:8080 and one for the server pointing to IP:11470 - both can be set to HTTPS with wildcard certs
- Access the webUI in a browser at https://subdomain1.domain.tls and then in Settings, set the server to https://subdomain2.domain.tld (no need to specify ports as that's taken care of by the reverse proxy)

The server should show up as ONLINE and video will play back within the browser - tested on Firefox and Safari in MacOS and Safari in iOS.

**Comment by HVR88** [comment]
I wrote this for tsaridas on the original docker git, so thought I'd include it here for reference. Feel free to pull anything from it later when you expand your docs.

# Self-hosted Stremio WebUI & Server<br>with Reverse Proxy & TLS/SSL on Own Domain Name

## Prerequisites

### Initial Stremio Account Setup

- Login ID/account for Stremio created at Stremio web site
- Your Stremio plugins installed via Stremio web site (Trakt, RD, etc.)


### For access with your own domain name and secure HTTPS access

- Valid and registered domain name
- Reverse Proxy installed on your network running on unique IP address (Nginx Proxy Manager, Caddy, Traefik, HAProxy, etc...)
- Wildcard certificate set up in reverse proxy for your domain name
- Some DNS service/capability (server, resolver, forwarder, black-hole) installed on your network with ability to set DNS records or overrides - PiHole, AdGuard Home, Unbound, DNSMasq, etc.
  (even a hosts file on an individual test machine can work)
 

### For remote access from outside your LAN

- VPN such as Tailscale, Netbird, Wireguard, ZeroTier, etc. (installed on all systems/OS you'll use/access)
  Must be installed along-side the reverse proxy if you want remote access to any URLS handled by the proxy
- Optional: Self-hosted Secure sign-on:: Authentik, Authelia, Keycloak, Zitadel, etc.
 

## Container and Reverse Proxy Setup

1. Install docker container on a Bridge network (uses host's IP with custom ports - usually default)
2. Test local access with IP address in browser
  Example: access webUI  http://10.10.1.200:8080 (use your specific IP)
3. Log in using the ID you previously created for Stremio
  All your plugins should be loaded automatically - verify this
4. Go to Settings and set Server address: http://10.10.1.200:11470 (always same IP but with server port 11470)
  Status must show "Online" after you enter the address
5. Browse the Stremio library, select a movie, select a source and try playing it
  Video should queue up and start playing in the browser
6. Create an entry in your reverse proxy for the webUI (example, "Proxy Hosts" in NPM)
  Domain name: stremio.yourdomain.tld
  Forward IP: 10.10.1.200	 Forward port: 8080
  Force TLS/SSL and select the wildcard certificate for your domain name (*.yourdomain.tld)
7. Create an entry in your reverse proxy for the server
  Domain name: stremio-server.yourdomain.tld
  Forward IP: 10.10.1.200	 Forward port: 11470
  Force TLS/SSL and select the wildcard certificate for your domain name (*.yourdomain.tld)
8. Create a DNS entry/override to point the two subdomains above to the IP of your reverse proxy
  Test local access via domain name in your browser
  Example: access webUI http://stremio-server.yourdomain.tld (don't use a port#, reverse proxy does that already)
  If reverse proxy is working and DNS entry correct, your browser will automatically be sent to webUI with https
9. Log in using the ID you previously created for Stremio
  You have to log in every time you connect with a different URL or a different browser
10. Go to Settings and set Server address: https://stremio-server.yourdomain.tld (note you don't need to include port#)
  Status must show "Online" after you enter the address
  This is important, as you have to set server address every time you use a new browser and AFTER logging in
11. Browse the Stremio library, select a movie, select a source and try playing it
  Video should queue up and start playing in the browser

If you have set up a VPN like Tailscale, the above will also automatically work when you access your network remotely
